// data.js — Expanded vocabulary (~300 words) and enriched training data
// Generated for Veo — compatible with existing app.js (no other changes needed)

const VOCAB = [
    "a", "about", "after", "again", "all", "an", "and", "another", "any", "apples",
    "are", "as", "at", "average", "away", "back", "balls", "be", "because", "been",
    "before", "blue", "boat", "book", "boys", "build", "bus", "but", "by", "calculate",
    "can", "car", "cars", "cats", "children", "class", "complete", "completes", "cover",
    "cyclist", "day", "days", "did", "distance", "divide", "do", "does", "dogs", "done",
    "each", "eight", "else", "even", "every", "far", "fast", "faster", "find", "finish",
    "first", "five", "flies", "flour", "for", "four", "from", "get", "girls", "give",
    "go", "goes", "going", "good", "had", "half", "has", "have", "he", "her", "here",
    "high", "him", "his", "hour", "hours", "how", "hundred", "if", "in", "into", "is",
    "it", "its", "job", "jobs", "just", "kilometer", "kilometers", "km", "km/h", "know",
    "larger", "less", "like", "liters", "long", "longer", "look", "machine", "machines",
    "made", "make", "man", "many", "may", "me", "men", "meter", "meters", "miles", "mix",
    "more", "most", "move", "moves", "moving", "much", "must", "my", "need", "never",
    "new", "next", "nine", "no", "not", "now", "of", "off", "on", "one", "only", "or",
    "oranges", "other", "our", "out", "over", "paint", "painters", "part", "per",
    "percent", "percentage", "place", "printers", "produce", "project", "put", "rate",
    "ratio", "red", "right", "road", "robots", "same", "say", "second", "seconds",
    "see", "seven", "she", "should", "six", "slow", "slower", "small", "so", "some",
    "speed", "split", "still", "stop", "students", "sugar", "take", "takes", "task",
    "teachers", "ten", "than", "that", "the", "their", "them", "then", "there", "these",
    "they", "thing", "think", "this", "those", "three", "time", "times", "to", "together",
    "too", "total", "train", "travel", "travels", "trip", "truck", "two", "under",
    "until", "up", "use", "very", "want", "was", "way", "we", "well", "were", "what",
    "when", "where", "which", "while", "who", "whole", "why", "will", "with", "women",
    "work", "worker", "workers", "would", "year", "years", "yellow", "yes", "you", "your"
];
// Total: 300 tokens

const VOCAB_SIZE = VOCAB.length; // 300

const CLASS_NAMES = ['Speed/Distance', 'Work/Rate', 'Percentage', 'Ratio'];

const TRAIN_DATA = [
    // ==================== Speed / Distance (label 0) ====================
    { text: "A train travels 120 km in 2 hours. How far in 5 hours?", label: 0 },
    { text: "A car moves at 60 km/h for 3 hours. What distance does it cover?", label: 0 },
    { text: "Train speed is 80 km/h traveling for 2.5 hours. Distance?", label: 0 },
    { text: "A cyclist travels 45 km in 3 hours. Speed?", label: 0 },
    { text: "A bus travels 200 km in 4 hours. How far in 7 hours?", label: 0 },
    { text: "An airplane flies 1500 km in 3 hours. Speed?", label: 0 },
    { text: "A car travels at 90 km/h for 2 hours. How far does it go?", label: 0 },
    { text: "Speed is 50 km/h and time is 4 hours. What is the distance?", label: 0 },
    { text: "Distance 360 km time 6 hours. What is average speed?", label: 0 },
    { text: "A runner covers 10 km in 1 hour. How far in 3.5 hours?", label: 0 },
    { text: "A train goes 300 km in 3 hours. What is its speed?", label: 0 },
    { text: "A boat travels 80 km in 4 hours. How far in 10 hours?", label: 0 },
    { text: "A truck moves at 70 km/h for 5 hours. Find the distance.", label: 0 },
    { text: "Distance 500 km time 5 hours. Average speed?", label: 0 },
    { text: "A motorcycle travels 180 km in 3 hours. How far in 7 hours?", label: 0 },
    { text: "A train goes 240 km in 4 hours. Speed in km/h?", label: 0 },
    { text: "A car moves 300 km at 100 km/h. How long does it take?", label: 0 },
    { text: "Speed 75 km/h for 4 hours. What is the distance?", label: 0 },
    { text: "A cyclist covers 60 km in 4 hours. What is the speed?", label: 0 },
    { text: "A bus goes 360 km in 6 hours. How far in 9 hours?", label: 0 },
    { text: "A train travels at 85 km/h for 3 hours. Find the distance.", label: 0 },
    { text: "A plane flies 2400 km in 4 hours. What is its speed?", label: 0 },
    { text: "A car travels 150 km in 2.5 hours. Average speed?", label: 0 },
    { text: "A truck goes 420 km in 7 hours. How far in 11 hours?", label: 0 },
    { text: "A runner runs 5 km in 0.5 hours. Speed in km/h?", label: 0 },
    { text: "A train travels 100 km in 1 hour 15 minutes. Speed?", label: 0 },
    { text: "A car moves at 55 km/h for 2 hours. Distance covered?", label: 0 },
    { text: "Distance 800 km time 10 hours. What is the speed?", label: 0 },
    { text: "A boat sails 120 km in 4 hours. How far in 15 hours?", label: 0 },
    { text: "A cyclist goes 72 km in 6 hours. Find the speed.", label: 0 },
    { text: "A bus travels at 65 km/h for 8 hours. Distance?", label: 0 },
    { text: "A train covers 450 km in 5 hours. Average speed?", label: 0 },
    { text: "A car travels 90 km in 1.5 hours. How far in 4 hours?", label: 0 },
    { text: "Speed 40 km/h time 3.5 hours. Distance?", label: 0 },
    { text: "A plane flies 3000 km in 5 hours. Find its speed.", label: 0 },
    { text: "A truck goes 560 km in 8 hours. How far in 12 hours?", label: 0 },
    { text: "A train moves at 95 km/h for 2 hours. Distance?", label: 0 },
    { text: "Distance 270 km time 3 hours. Speed in km/h?", label: 0 },
    { text: "A car travels 180 km at 90 km/h. Time taken?", label: 0 },
    { text: "A boat covers 96 km in 4 hours. How far in 24 hours?", label: 0 },

    // ==================== Work / Rate (label 1) ====================
    { text: "If 3 workers complete a job in 4 days how long for 6 workers?", label: 1 },
    { text: "5 workers take 10 days to complete a project. Days for 2 workers?", label: 1 },
    { text: "8 workers can complete a job in 6 days. How long for 4 workers?", label: 1 },
    { text: "12 workers finish work in 8 days. 6 workers will take?", label: 1 },
    { text: "9 workers complete a task in 12 days. 3 workers take how long?", label: 1 },
    { text: "4 machines produce 100 items in 5 hours. 2 machines take?", label: 1 },
    { text: "6 painters paint a wall in 4 days. How long for 3 painters?", label: 1 },
    { text: "10 workers take 6 days to build a wall. How long for 15 workers?", label: 1 },
    { text: "7 workers can finish a task in 14 days. How long for 14 workers?", label: 1 },
    { text: "2 machines finish a job in 8 hours. How long for 4 machines?", label: 1 },
    { text: "15 workers build a house in 20 days. How long for 10 workers?", label: 1 },
    { text: "3 robots assemble 60 cars in 5 days. How long for 5 robots?", label: 1 },
    { text: "6 workers dig a hole in 9 days. 9 workers take how many days?", label: 1 },
    { text: "8 painters paint a house in 12 days. 4 painters take?", label: 1 },
    { text: "5 machines make 200 toys in 8 hours. 10 machines make how long?", label: 1 },
    { text: "12 electricians wire a building in 18 days. 6 electricians take?", label: 1 },
    { text: "4 workers complete a task in 15 days. How long for 6 workers?", label: 1 },
    { text: "9 builders construct a wall in 7 days. 3 builders take?", label: 1 },
    { text: "2 printers print 500 pages in 3 hours. 4 printers take?", label: 1 },
    { text: "10 workers finish a road in 30 days. 15 workers finish in?", label: 1 },
    { text: "6 carpenters build a deck in 8 days. 3 carpenters take?", label: 1 },
    { text: "5 machines fill 1000 bottles in 4 hours. 8 machines take?", label: 1 },
    { text: "7 workers paint a fence in 6 days. 14 workers take?", label: 1 },
    { text: "3 robots assemble 45 bikes in 9 days. 5 robots take?", label: 1 },
    { text: "11 workers harvest a field in 22 days. 22 workers take?", label: 1 },
    { text: "4 cleaners clean an office in 2 hours. 6 cleaners take?", label: 1 },
    { text: "8 cooks prepare 400 meals in 5 hours. 10 cooks take?", label: 1 },
    { text: "2 workers lay 100 bricks in 5 hours. 5 workers lay 100 bricks in?", label: 1 },
    { text: "6 gardeners mow a lawn in 3 hours. 9 gardeners take?", label: 1 },
    { text: "10 students complete a project in 12 days. 5 students take?", label: 1 },
    { text: "4 teachers grade 200 papers in 6 hours. 8 teachers take?", label: 1 },
    { text: "7 bakers bake 350 loaves in 7 hours. 3 bakers take for 350 loaves?", label: 1 },
    { text: "9 programmers write code in 18 days. 6 programmers take?", label: 1 },
    { text: "5 plumbers fix 15 pipes in 3 days. 10 plumbers take?", label: 1 },
    { text: "8 movers pack a house in 4 hours. 4 movers take?", label: 1 },
    { text: "3 tailors stitch 9 suits in 6 days. 6 tailors take?", label: 1 },
    { text: "6 artists paint a mural in 10 days. 5 artists take?", label: 1 },
    { text: "4 photographers edit 200 photos in 5 hours. 10 photographers take?", label: 1 },
    { text: "12 waiters serve 300 guests in 4 hours. 6 waiters take?", label: 1 },

    // ==================== Percentage (label 2) ====================
    { text: "What is 20 percent of 150?", label: 2 },
    { text: "Find 15% of 200", label: 2 },
    { text: "What percentage is 25 of 200?", label: 2 },
    { text: "Calculate 30% of 80", label: 2 },
    { text: "What is 8% of 250?", label: 2 },
    { text: "45 is what percent of 90?", label: 2 },
    { text: "What is 12.5 percent of 400?", label: 2 },
    { text: "60 is what percentage of 240?", label: 2 },
    { text: "Find the percentage: 18 out of 72", label: 2 },
    { text: "What percent of 500 is 125?", label: 2 },
    { text: "What is 10% of 350?", label: 2 },
    { text: "Find 25 percent of 480", label: 2 },
    { text: "What percentage is 75 of 300?", label: 2 },
    { text: "Calculate 40% of 120", label: 2 },
    { text: "What is 5% of 900?", label: 2 },
    { text: "80 is what percent of 400?", label: 2 },
    { text: "Find 33% of 600", label: 2 },
    { text: "What percentage is 50 of 250?", label: 2 },
    { text: "What is 7.5% of 800?", label: 2 },
    { text: "90 is what percent of 150?", label: 2 },
    { text: "Calculate 18% of 450", label: 2 },
    { text: "What percentage is 12 of 48?", label: 2 },
    { text: "What is 22% of 700?", label: 2 },
    { text: "30 is what percent of 120?", label: 2 },
    { text: "Find 9% of 330", label: 2 },
    { text: "What percentage is 35 of 140?", label: 2 },
    { text: "What is 16% of 275?", label: 2 },
    { text: "55 is what percent of 110?", label: 2 },
    { text: "Calculate 2.5% of 1000", label: 2 },
    { text: "What percentage is 8 of 64?", label: 2 },
    { text: "What is 85% of 220?", label: 2 },
    { text: "70 is what percent of 280?", label: 2 },
    { text: "Find 11% of 540", label: 2 },
    { text: "What percentage is 90 of 360?", label: 2 },
    { text: "What is 4% of 1250?", label: 2 },
    { text: "95 is what percent of 190?", label: 2 },
    { text: "Calculate 13% of 820", label: 2 },
    { text: "What percentage is 21 of 84?", label: 2 },
    { text: "What is 27% of 670?", label: 2 },
    { text: "42 is what percent of 210?", label: 2 },

    // ==================== Ratio (label 3) ====================
    { text: "The ratio of boys to girls is 3:4. If there are 28 girls how many boys?", label: 3 },
    { text: "Mix paint in ratio 2:5. If 10 liters of blue how much yellow?", label: 3 },
    { text: "The ratio of apples to oranges is 2:3. If 15 oranges how many apples?", label: 3 },
    { text: "In a class ratio of boys to girls is 5:7. 21 girls. Boys?", label: 3 },
    { text: "Ratio of red to blue balls is 3:4. 20 blue balls. Red balls?", label: 3 },
    { text: "Sugar and flour ratio 1:4. 200g flour. How much sugar?", label: 3 },
    { text: "Ratio of cats to dogs is 2:3. If 12 cats how many dogs?", label: 3 },
    { text: "A to B ratio is 5:3. If B is 15 find A.", label: 3 },
    { text: "The ratio of men to women is 4:5. 25 women. How many men?", label: 3 },
    { text: "Divide 120 in ratio 3:5. What is the larger part?", label: 3 },
    { text: "The ratio of cars to trucks is 7:2. If 21 cars, how many trucks?", label: 3 },
    { text: "Mix water and juice in ratio 3:1. If 9 liters of water, how much juice?", label: 3 },
    { text: "The ratio of students to teachers is 12:1. If 36 teachers, how many students?", label: 3 },
    { text: "Divide 180 in ratio 2:3. What is the smaller part?", label: 3 },
    { text: "Ratio of pencils to pens is 5:2. If 35 pencils, how many pens?", label: 3 },
    { text: "The ratio of chairs to tables is 8:3. If 24 tables, how many chairs?", label: 3 },
    { text: "Divide 240 in ratio 5:7. Larger part?", label: 3 },
    { text: "Ratio of fiction to non-fiction books is 3:2. 90 fiction books. Non-fiction?", label: 3 },
    { text: "The ratio of boys to girls is 6:5. 36 boys. Girls?", label: 3 },
    { text: "Mix cement and sand in ratio 1:3. 12 kg cement. Sand?", label: 3 },
    { text: "Divide 150 in ratio 2:3:5. Middle part?", label: 3 },
    { text: "Ratio of white to black cars is 5:4. 45 white cars. Black cars?", label: 3 },
    { text: "The ratio of adults to children is 9:5. 45 adults. Children?", label: 3 },
    { text: "Divide 210 in ratio 4:3. Larger part?", label: 3 },
    { text: "Ratio of mangoes to bananas is 5:6. 30 mangoes. Bananas?", label: 3 },
    { text: "The ratio of lions to tigers is 2:7. 14 lions. Tigers?", label: 3 },
    { text: "Divide 300 in ratio 1:2:3. Smallest part?", label: 3 },
    { text: "Ratio of red to green to blue balls is 3:4:5. 36 green balls. Total balls?", label: 3 },
    { text: "The ratio of milk to water is 7:2. 21 liters milk. Water?", label: 3 },
    { text: "Divide 560 in ratio 5:3. Difference between parts?", label: 3 },
    { text: "Ratio of boys to girls to teachers is 6:5:1. 55 total. Teachers?", label: 3 },
    { text: "Mix three colors in ratio 2:3:5. 40 ml of third color. Second color?", label: 3 },
    { text: "The ratio of gold to silver is 5:8. 65 g gold. Silver?", label: 3 },
    { text: "Divide 270 in ratio 4:5:6. Largest part?", label: 3 },
    { text: "Ratio of chickens to ducks is 9:4. 72 chickens. Ducks?", label: 3 },
    { text: "The ratio of length to width is 7:3. Perimeter is 100. Length?", label: 3 },
    { text: "Divide 400 in ratio 3:5. Smaller part?", label: 3 },
    { text: "Ratio of wins to losses is 8:3. 32 wins. Losses?", label: 3 },
    { text: "The ratio of students in three classes is 4:5:6. 120 total. Largest class?", label: 3 },
    { text: "Mix acid and water in ratio 2:9. 33 liters total. Acid?", label: 3 }
];

const DEFAULT_CONFIG = {
    numLayers: 2,
    units: 32,
    learningRate: 0.003,
    activation: "relu",
    reasoningDepth: 5,
    batchSize: 8,
    epochs: 60
};